name: Deno lint fmt

on: [push, pull_request]

jobs:
  deno_lint_fmt:
    name: Lint Format and Test all deno files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Deno fmt check
        run: deno fmt --check

      - name: Run Deno lint
        run: deno lint
